export { Header } from "./header";
export { Footer } from "./footer";
export { Image } from "./image";
export { VideoArea } from "./videoArea";
export { Information } from "./information";
export { Layout } from "./layout/layout";
export { Menus } from './elements/menus';
export { AboutArea } from './aboutArea';
export { BusinessArea } from './businessArea';